typography_spectrum: 0.7954272569622844
color:
  brandStrength: 0.533021800685674
  lightness: 0.5697853046003729
  saturation: 0.2519660824909806
  rhythmicContrast: 0.871607479872182
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
opengraph:
  type: ''
layout_spectrum: 0.04652243386954069
author:
  email: boris@bmannconsulting.com
  url: 'http://www.bmannconsulting.com'
  name: Boris Mann
name: Pudding
title: Professional web apps on the desktop
